export type personalId = {
	DocRegNo: string;
	IssuingDate: string;
	ExpiryDate: string;
	IssuingAuthority: string;
	PersonalNumber: string;
	Surname: string;
	GivenName: string;
	ParentGivenName: string;
	Sex: string;
	PlaceOfBirth: string;
	CommunityOfBirth: string;
	StateOfBirth: string;
	DateOfBirth: string;
	State: string;
	Community: string;
	Place: string;
	Street: string;
	HouseNumber: string;
	AddressDate: string;
	Entrance: string;
	Floor: string;
	AppartmentNumber: string;
	Image: string;
};
